services:
  mongo:
    image: mongo:latest
    container_name: Mongo-Chat-App
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chat-app
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
